---
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://user:password@localhost:8888}
      enabled: true
    discovery:
      enabled: true
      serviceId: Config-Server
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 300
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka
logging:
  level:
    ROOT: WARN
    com.sarbesh: INFO