#Disable security of the Management endpoint
management:
  security:
    enabled: false

security:
  network:
    access-control:
      enable: true
      secret: "my-Network-Secuiiryt-Access"
      header: "x-network-access"
      ignoreApi:
        - "/actuator/**"

jwt:
  signingKey: "My-Jwt-secRetKey"
  token:
    validity: 18000
    prefix: "Bearer "
  authorities:
    key: "roles"
  header:
    string: "Authorization"