---
spring:
  profiles:
    group:
      local: local-security
#  sleuth:
#    baggage:
#      correlation-fields:
#        - "Method"
#        - "Uri"
#        - "Query"
#        - "User-Agent"
#        - "Remote"
#        - "App-Name"
#        - "UUID"

logging:
  pattern:
    level: "%5p |${spring.application.name}|%X{traceId:-}|%X{spanId:-}|%X{Method}|%X{Uri}|%X{Query}|%X{User-Agent}|%X{Remote}|%X{UUID}|"