---
spring:
  profiles:
    group:
      local: local-security
#  sleuth:
#    baggage:
#      correlation-fields:
#        - "Method"
#        - "Uri"
#        - "Query"
#        - "User-Agent"
#        - "Remote"
#        - "App-Name"
#        - "UUID"

#logging:
#  pattern:
#    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}] [%X{ddd:-},%X{bp:-},%X{bpids:-}] [%X{op:-},%X{chunk:-},%X{i:-}]"
logging:
  pattern:
    level: "%5p [%X{App-Name:${spring.application.name}}|%X{spanId:-}|%X{traceId:-}|%X{Method}|%X{Uri}|%X{Query}|%X{User-Agent}|%X{Remote}|%X{UUID}] - %m%n"