---
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://user:password@localhost:8888}
      enabled: true
  security:
  	user:
	  password: ${PASSWORD:password}
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka
