---
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://user:password@localhost:8888}
      enabled: true

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 300
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka
    instance:
      nonSecurePort: 80
      securePortEnabled: true
      securePort: 443
      leaseRenewalIntervalInSeconds: 180
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    ROOT: WARN
    com.sarbesh: INFO

#Disable security of the Management endpoint
management:
  security:
    enabled: false
