---
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://user:password@localhost:8888}
      enabled: true

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 300
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka
  instance:
    hostname: ${HOST_NAME:localhost}
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    secureHealthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    nonSecurePort: 80
    securePortEnabled: true
    securePort: 443
    leaseRenewalIntervalInSeconds: 180
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

logging:
  level:
    ROOT: WARN
    com.sarbesh: INFO

#Disable security of the Management endpoint
management:
  security:
    enabled: false
