---
spring:
  profiles:
    group:
      local: local-security
      prod: prod-security

logging:
  pattern:
    level: "%5p |${spring.application.name}|%X{traceId:-}|%X{spanId:-}|%X{Method}|%X{Uri}|%X{Query}|%X{User-Agent}|%X{Remote}|%X{UUID}|"