---
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
      uri: ${CONFIG_SERVER_URL:http://user:password@localhost:8888}
      enabled: true
  security:
    user:
      password: ${PASSWORD:password}

eureka:
  client:
    registerWithEureka: ${EUREKA_REGISTER:false}
    fetchRegistry: ${EUREKA_FETCH:false}
    region: default
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka
  instance:
    hostname: ${HOST_NAME:localhost}
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    secureHealthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    nonSecurePort: 80
    securePortEnabled: true
    securePort: 443
    leaseRenewalIntervalInSeconds: 1800
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


logging:
  level:
    ROOT: INFO
    com.sarbesh: DEBUG