---
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 120
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka
  instance:
    metadataMap:
      user: user
      password: ${spring.cloud.config.server.git.password}
      configPath: /config
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}