---
accessPolicies:
  admins:
    - api:
        - url: "/actuator/**"
          httpMethod:
            - "POST"
            - "GET"
        - url: "/encrypt"
          httpMethod:
            - "POST"
        - url: "/decrypt"
          httpMethod:
            - "POST"
      allowedRoles:
        - "ADMIN"