---
spring:
  security:
    user:
      password: ${spring.cloud.config.server.git.password}

#Disable security of the Management endpoint
management:
  security:
    enabled: false

security:
  network:
    access-control:
      enable: false