---
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 120
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka
  instance:
#    hostname: ${vcap.application.uris[0]:Config-Server}
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 180
    metadataMap:
      user: user
      password: ${spring.cloud.config.server.git.password}
      configPath: /config
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}