---
eureka:
  instance:
    metadataMap:
      user: user
      password: ${spring.cloud.config.server.git.password}
      configPath: /config
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}