---
spring:
  profiles:
    include: eureka,security,peer

logging:
  level:
    ROOT: INFO
    com.sarbesh.eurekaserver: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${PORT:8761}