---
spring:
  profiles:
    group:
      local: routes,policy,policy-login,policy-registration
      prod: routes,policy,policy-login,policy-registration

management:
  endpoints:
    web:
      exposure:
        include: "*"