---
spring:
  cloud:
    gateway:
      routes:
        - id: signOn
          uri: lb://Login-service
          predicates:
            - Path=/api/prelogin/auth/passwordLogin
          filters:
            - StripPrefix=0
        - id: userRegistation
          uri: lb://User-Registration
          predicates:
            - Path=/prelogin/register/user
          filters:
            - StripPrefix=2