---
spring:
  cloud:
    gateway:
      routes:
        - id: signOn
          uri: lb://Login
          predicates:
            - Path=/prelogin/login/**
          filters:
            - StripPrefix=2
        - id: userRegistation
          uri: lb://User-Registration
          predicates:
            - Path=/prelogin/register/user
          filters:
            - StripPrefix=2